# segunda versão da sintaxe do docker-compose
version: '2'

# volumes para dados persistentes
volumes:
  # persistiremos os dados do MySQL
  manager-mysql-data:
    driver: local
  # persistiremos os dados do Redis
  #manager-redis-data:
    #driver: local

services:
  
  # MySQL 5.7, mas você poderia rodar outra versão
  # apenas alterando o numero na linha abaixo
  mysql:
    image: ambientum/mysql:5.7
    container_name: manager-mysql
    volumes:
      - manager-mysql-data:/var/lib/mysql
      - .:/var/www/app
    ports:
      - "3306:3306"
    # definicao das senhas do mysql, ajuste como quiser
    environment:
      - MYSQL_ROOT_PASSWORD=manager
      - MYSQL_DATABASE=manager
      - MYSQL_USER=root
      - MYSQL_PASSWORD=manager

  # Redis
  #cache:
    #image: ambientum/redis:3.2
    #container_name: manager-redis
    #command: --appendonly yes
    #volumes:
      #- manager-redis-data:/data
    #ports:
      #- "6379:6379"

  # PHP WEB, voce pode trocar o caddy por nginx ou apache, 
  # a escolha é sua
  app:
    image: ambientum/php:7.1-apache
    container_name: manager-php
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      #- cache

  # Laravel Queues
  #queue:
    #image: ambientum/php:7.0
    #container_name: manager-queue
    #command: php artisan queue:listen
    #volumes:
      #- .:/var/www/app
    #links:
      #- mysql
      #- cache